version: '3.1'

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      MONGODB_USER: ${USER}
      MONGODB_PASS: ${PASSWORD}
    volumes:
      - ./docker/config/mongo.yml:/etc/mongo/mongo.yml
      - ./data:/data/db
    ports:
      - 27017:27017
    command: mongod --config /etc/mongo/mongo.yml